-- =====================================================================
-- Cadastros de clientes, fornecedores e transportadoras
--   * código sequencial (gerado sozinho, único)
--   * nome fantasia separado da razão social (a razão social continua em "nome",
--     que é o que vai na NF-e)
--   * endereço completo de fornecedores e transportadoras (busca pelo CEP)
-- Documentos, telefones e CEP são gravados só com números; a tela aplica as máscaras.
-- =====================================================================

alter table public.clientes
  add column codigo bigint generated by default as identity,
  add column nome_fantasia text;
alter table public.clientes add constraint clientes_codigo_key unique (codigo);

alter table public.fornecedores
  add column codigo bigint generated by default as identity,
  add column nome_fantasia text,
  add column cep text,
  add column logradouro text,
  add column numero text,
  add column complemento text,
  add column bairro text;
alter table public.fornecedores add constraint fornecedores_codigo_key unique (codigo);

alter table public.transportadoras
  add column codigo bigint generated by default as identity,
  add column nome_fantasia text,
  add column inscricao_estadual text,
  add column cep text,
  add column logradouro text,
  add column numero text,
  add column complemento text,
  add column bairro text,
  add column municipio text,
  add column uf text;
alter table public.transportadoras add constraint transportadoras_codigo_key unique (codigo);
